backend:
  name: github
  repo: The64thGamer/cheeseepedia
  use_graphql: false
  open_authoring: true
  base_url: https://sveltia-cms-auth.a22j2udvt.workers.dev

media_folder: "static/photos" # Media files will be stored in the repo under static/images/uploads
public_folder: "/photos" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://cheeseepedia.org
display_url: https://cheeseepedia.org
publish_mode: editorial_workflow

collections:
  - name: "Animatronic Shows"
    label: "Animatronic Shows"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Animatronic Shows"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Stage Variations"
    label: "Stage Variations"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Stage Variations"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Animatronics"
    label: "Animatronics"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Animatronics"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Retrofits"
    label: "Retrofits"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Retrofits"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Costumed Characters"
    label: "Costumed Characters"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Costumed Characters"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Animatronic Repair & Preservation"
    label: "Animatronic Repair & Preservation"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Animatronic Repair & Preservation"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Showtapes"
    label: "Showtapes"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Showtapes"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Showtape Formats"
    label: "Showtape Formats"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Showtape Formats"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Live Shows"
    label: "Live Shows"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Live Shows"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Showtape Puppets"
    label: "Showtape Puppets"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Showtape Puppets"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Family Vision"
    label: "Family Vision"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Family Vision"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "ShowBiz Pizza Programs"
    label: "ShowBiz Pizza Programs"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "ShowBiz Pizza Programs"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Merchandise"
    label: "Merchandise"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Merchandise"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Menu Items"
    label: "Menu Items"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Menu Items"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Tokens"
    label: "Tokens"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Tokens"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Tickets"
    label: "Tickets"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Tickets"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Movies"
    label: "Movies"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Movies"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Video Games"
    label: "Video Games"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Video Games"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Locations"
    label: "Locations"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Locations"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Arcade Games"
    label: "Arcade Games"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Arcade Games"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Employee Wear"
    label: "Employee Wear"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Employee Wear"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Remodels & Initiatives"
    label: "Remodels & Initiatives"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Remodels & Initiatives"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Store Fixtures"
    label: "Store Fixtures"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Store Fixtures"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Ad Vehicles"
    label: "Ad Vehicles"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Ad Vehicles"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Animatronic Control Systems"
    label: "Animatronic Control Systems"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Animatronic Control Systems"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Other Systems"
    label: "Other Systems"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Other Systems"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Programming Systems"
    label: "Programming Systems"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Programming Systems"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Promotional Material"
    label: "Promotional Material"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Promotional Material"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Documents"
    label: "Documents"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Documents"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Corporate Documents"
    label: "Corporate Documents"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Corporate Documents"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Training, Updates, & Company Media"
    label: "Training, Updates, & Company Media"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Training, Updates, & Company Media"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "News Footage"
    label: "News Footage"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "News Footage"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "History"
    label: "History"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "History"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Events"
    label: "Events"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Events"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Characters"
    label: "Characters"
    folder: "content/wiki/"
    create: true
    filter: {field: "tags", value: "Characters"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Commercials" # Used in routes, e.g., /admin/collections/blog
    label: "Commercials" # Used in the UI
    folder: "content/wiki/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    filter: {field: "tags", value: "Commercials"}
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Transcriptions" # Used in routes, e.g., /admin/collections/blog
    label: "Transcriptions" # Used in the UI
    folder: "content/transcriptions/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Users" # Used in routes, e.g., /admin/collections/blog
    label: "Users" # Used in the UI
    folder: "content/users/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Meta" # Used in routes, e.g., /admin/collections/blog
    label: "Meta Page" # Used in the UI
    folder: "content/meta/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Photo" # Used in routes, e.g., /admin/collections/blog
    label: "Photo" # Used in the UI
    folder: "content/photos/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }

  - name: "Video" # Used in routes, e.g., /admin/collections/blog
    label: "Video" # Used in the UI
    folder: "content/videos/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: html
    format: toml-frontmatter
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "text" }